Frantz-B/Kargo_QA_Release-Notes

README.md

- Interesting, seem this follow similar flow like tagging where probably part of the commit message is not found in Write area of pull request

Initial branch addition - pr

---

README.md
release-notes-helper.js

Currently v1 does the following:
- collects all the PR elements info
- parses it so that it's ready for pasting text copied, into release tag for other projects

Finally updated this repo to be Automated - v1

---

release-notes-helper.js

- Learned to be careful with the forEach and resetting the string after
- Happy I kept testing

v2: Add logic for sorting stories vs bugs

---

release-notes-helper.js

- Changing regex for DM id plucking
- Changing regex for ticket title plucking (spent a long time on this trying only regex instead of regex & js
- Adding updated regex to be project agnostic and better formatting for multiple tickets
⚠️ - I am aware that with the new regex, any actual number in the title will make it pick up like a jira ticket but this is the price to pay when loosing the regex at this point in time

v3: Title and updated regex

---

release-notes-helper.js

♻️ 🔥 👨🏿‍💻  Wadah's original base code that showed me the light

---

release-notes-helper.js

♻️ 👨🏿‍💻  Add slack markdown and pluck out jira tickets from PRs

---

release-notes-helper.js

♻️ 🔥 👨🏿‍💻  - Tap into Gihhub APIs directly & have section for WIP PRs

---

release-notes-helper.js

🔥 👨🏿‍💻  - Fixed sectional pasting of code in console by adding awaits

---

release-notes-helper.js

* Add KBR, Deal-Sync, and Sync-Diff
* Add Error handling 
* Remove Anonymous Functions
📌  - https://kargo1.atlassian.net/browse/QA-137

👨🏿‍💻  🔧  - QA-137: Add Error Handling, Make functions non-anonymous, and add projects

---

release-notes-helper.js

* Fixing empty lines found after sorting PRs into 3 categories
📌 - https://kargo1.atlassian.net/browse/QA-148
📝 - It's suppose to fix the following:

👨🏿‍💻 🔧 QA-148: Fixing empty lines found after sorting PRs into 3 categories

---

.github/workflows/label.yml
pull_request_template.md

* Adding YML file to automate adding Labels to PR when:
* PR title contains the word `bug`
* PR title contains the word `feat1
* PR is Closed
* Adding PR template also
* KM ticket: https://kargo1.atlassian.net/browse/KME-7936

🤖 🏗️ - [KME-7936]: Automating Labels and Template for PRs

---

.github/workflows/label.yml

* Adding secrets.token
* KM ticket: https://kargo1.atlassian.net/browse/KME-7925

🤖🧹 - [KME-7936]: Part2_Adding secrets.token

---

.github/workflows/label.yml

* Adding secrets.token
* KM ticket: https://kargo1.atlassian.net/browse/KME-7925

🤖🧹 -[KME-7936] : Updating git actions YML again

---

.github/workflows/label.yml

* Adding secrets.token
* KM ticket: https://kargo1.atlassian.net/browse/KME-7925

🤖🧹 - [KME-7936] : Updating git actions YML to run with each step

---

.github/workflows/label.yml

* Adding YML file to automate adding Labels to PR when:
* PR has merge conflicts
* Quick update to read me
* KM ticket: https://kargo1.atlassian.net/browse/KME-7950

🤖🔧 - [KME-7950] : feat - Adding label to PR when it has merge  and update on Readme

---

main.js

* Adding Ad-Tag projects to repo:
* https://github.com/KargoGlobal/retail-api              Retail API
- https://github.com/KargoGlobal/ad-kailtra              Kalitra
- https://github.com/KargoGlobal/ad-platform-templates   Ad Platform
- https://github.com/KargoGlobal/ad-demo-platform        Demo Site
- https://github.com/KargoGlobal/ad-composer-react       Ad Composer React      
- https://github.com/KargoGlobal/ad-composer             ABA Previewer 
- https://github.com/KargoGlobal/ad-snippet-service      Snippet Service
- https://github.com/KargoGlobal/ad-tag                  Ad Tag
- https://github.com/KargoGlobal/ad-krossbow             Krossbow / Ad Tag E2E Testing
- https://github.com/KargoGlobal/ad-kargonaut            Kargonaut 
* KM ticket: …

feat - 🚀 - Adding Ad-tag Projects to Release Notes Generator

---

main.js

* Fix the Kailtra name spelling
* Ticket: [KAT-5506](https://kargo1.atlassian.net/browse/KAT-5506)

:wrench: - Fixing the Kailtra name spelling

---

main.js

* Adding KAIL and COP projects
* https://kargo1.atlassian.net/browse/KAT-5506

KAT-5506: 🔧 - Adding KAIL and COP projects

---

main.js

* Adding KOALA repo
* KAT ticket: https://kargo1.atlassian.net/browse/KAT-5938

🔧  - [KAT-5938] : Add KOALA Ad-tag repo to Release Notes Generator

---

.github/workflows/generate_notes.yml

* 🤖 - [KME-9699] : bug - Adding suggest fixed for github action
* KM ticket: [KME-9699]

🤖 - [KME-9699] : bug - Adding suggest fixes for github action
